Traceback (most recent call last):
  File "c:\Users\jonma\Documents\GitHub\Python-Exercises\Useful_modules\traceback_module.py", line 28, in <module>
    raise ValueError("An example exception")
ValueError: An example exception
